stages:
  - build
  - test
  - deploy_to_k8s

variables:
  IMAGE_NAME: firstservlet
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  CONTAINER_NAME: my-app

build:
  stage: build
  script:
    - mvn clean package
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
  artifacts:
    paths:
      - target/*.jar
  tags:
    - shell
  only:
    - main

test:
  stage: test
  script:
    - docker run -d --name $CONTAINER_NAME -p 8080:8080 -m 1g    $IMAGE_TAG
    - sleep 5
    - curl -f http://localhost:8080 || exit 1
    - docker stop $CONTAINER_NAME
    - docker rm $CONTAINER_NAME
  tags:
    - shell
  only:
    - main

deploy:
  stage: deploy_to_k8s
  image: bitnami/kubectl:latest
  script:
    - kubectl config use-context docker-desktop
    - kubectl apply -f deployment.yaml
    - docker stop $CONTAINER_NAME || true
    - docker rm $CONTAINER_NAME || true
    - docker run -d --name $CONTAINER_NAME -p 8080:8080 -m 1g $IMAGE_TAG
  tags:
    - shell
  only:
    - main
